# general
batch_size: 128
input_size: 112
embd_shape: 512
data_name: 'K-Face'
sub_name: 'roi-kceleb-Res' # 'arc_res50', 'arc_mbv2', 'arc_res50_merge', 'arc_mbv2_masked'
backbone_type: 'ResNet50' # 'ResNet50', 'MobileNetV2'
head_type: ArcHead
is_ccrop: False # central-cropping or not

train_dataset: './data/tfrecord/kface_bin.tfrecord'
binary_img: True
num_classes: 100
num_samples: 12052
epochs: 50
base_lr: 0.0001
w_decay: !!float 5e-4
save_steps: 940 # num_samples // batch_size * 10